//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQRSService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaPodaci
    {
        public string AutorRevizije { get; set; }
        public System.DateTime DatumKreiranjaRevizije { get; set; }
        public int RedniBrojRevizije { get; set; }
        public string JedinstvenaOznakaRevizije { get; set; }
    }
}
